title: Summer Capstone practice
logo: /assets/img/logo.png
description: Demoing some altair interactive charts
show_downloads: false
repository: elleobrien/summer-capstone-practice
google_analytics: 
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
